### ISSUE TITLE
수정 건의

### ISSUE THREAD

**Issue by LocketGoma** [Sessho-maru/pbfWalker#1]
풀 리퀘스트 하려니까 제한 걸려있는거같아서 안되네요

convert_ms_to_human_readable에서 값을 변환해주는 부분의 경우,
hour는 %24를 빼주는것이 좋아보입니다.

시간 표기인데, 시간표기에서 %24를 해버리면 극단적인 경우 (영상 길이가 24시간을 넘는 경우)에는 제대로 체크가 되지 않습니다.

```
def convert_ms_to_human_readable(ms):
	ms = int(ms)
	s = (ms / 1000) % 60
	s = int(s)
	m = (ms / ( 1000*60 )) % 60
	m = int(m)
	h = (ms / ( 1000*60*60 ))   #시간에 %24를 해버리면 극단적인 경우 (24시간 이상 길이의 영상)은 캐치가 제대로 안됨.
	h = int(h)
	return [h, m, s, ms % 1000]
```

확인해보시고 의견 혹은 적용 부탁드립니다.

**Comment by Sessho-maru** [comment]
> 풀 리퀘스트 하려니까 제한 걸려있는거같아서 안되네요
> 
> convert_ms_to_human_readable에서 값을 변환해주는 부분의 경우,
> hour는 %24를 빼주는것이 좋아보입니다.
> 
> 시간 표기인데, 시간표기에서 %24를 해버리면 극단적인 경우 (영상 길이가 24시간을 넘는 경우)에는 제대로 체크가 되지 않습니다.
> 
> ```
> def convert_ms_to_human_readable(ms):
> 	ms = int(ms)
> 	s = (ms / 1000) % 60
> 	s = int(s)
> 	m = (ms / ( 1000*60 )) % 60
> 	m = int(m)
> 	h = (ms / ( 1000*60*60 ))   #시간에 %24를 해버리면 극단적인 경우 (24시간 이상 길이의 영상)은 캐치가 제대로 안됨.
> 	h = int(h)
> 	return [h, m, s, ms % 1000]
> ```
> 
> 확인해보시고 의견 혹은 적용 부탁드립니다.

아하, 저런 문제가 있었군요
다음팟플레이어가 1일단위를 표시하는지는 모르겠지만
일단 h 의 %24 는 빼버리겠습니다

**Comment by LocketGoma** [comment]
감사합니다.

아 그리구 이슈 깔끔히 해결됐다 싶으시면 이슈 닫아주세여 해결되고 열려있으면 표시가 계속 뜨더라구요
일단 닫아놓겠습니다. 즐거운 코딩라이프되세요
